# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: bank.proto for package 'bank'

require 'grpc'
require 'bank_pb'

module Bank
  module WalletService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'bank.WalletService'

      rpc :GetByUserID, GetByUserIDRequest, GetByUserIDResponse
      rpc :AddPayments, AddPaymentsRequest, AddPaymentsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
