# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "bank.GetByUserIDRequest" do
    optional :user_id, :int32, 1
  end
  add_message "bank.GetByUserIDResponse" do
    optional :wallet, :message, 1, "bank.Wallet"
  end
  add_message "bank.AddPaymentsRequest" do
    optional :user_id, :int32, 1
    repeated :payments, :message, 2, "bank.Payment"
  end
  add_message "bank.AddPaymentsResponse" do
    optional :wallet, :message, 1, "bank.Wallet"
  end
  add_message "bank.User" do
    optional :id, :int32, 1
    optional :name, :string, 2
  end
  add_message "bank.Wallet" do
    optional :id, :int32, 1
    optional :total, :int32, 2
    repeated :recent_payments, :message, 3, "bank.Payment"
  end
  add_message "bank.Payment" do
    optional :id, :int32, 1
    optional :amount, :int32, 2
    optional :target, :string, 3
    optional :reason, :string, 4
  end
end

module Bank
  GetByUserIDRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bank.GetByUserIDRequest").msgclass
  GetByUserIDResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bank.GetByUserIDResponse").msgclass
  AddPaymentsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("bank.AddPaymentsRequest").msgclass
  AddPaymentsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("bank.AddPaymentsResponse").msgclass
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("bank.User").msgclass
  Wallet = Google::Protobuf::DescriptorPool.generated_pool.lookup("bank.Wallet").msgclass
  Payment = Google::Protobuf::DescriptorPool.generated_pool.lookup("bank.Payment").msgclass
end
